### ISSUE TITLE
DatabaseReference.updateChildren with booleans sets 0/1 instead of false/true in iOS

### ISSUE THREAD

**Issue by pauminku** [GitLiveApp/firebase-kotlin-sdk#275]
executing this:
`childUpdates["yourTurn"] = false; database.updateChildren(childUpdates)`

in Android is saving it correctly. In RealtimeDatabase console I can see: 
`yourTurn: false`

but in iOS it's saving it as int:
`yourTurn: 0`

**Expected behabiour:**
it should save it as a boolean in iOS as well

**Comment by pauminku** [comment]
related issue: https://github.com/JetBrains/kotlin-native/issues/3857

**Comment by nbransby** [comment]
thanks for reporting, if you can find the time to submit PR with a failing test that would be much appreciated!

**Comment by SuperCaliMan** [comment]
Same problem

**Comment by alperenbabagil** [comment]
Same here

**Comment by b95505017** [comment]
It looks like this kind of issue would happen on all kmm libraries which use iOS(darwin) library directly instead of  use pure kotlin code.

**Comment by JoseTripianaZapp** [comment]
Hello, do you have any date to release this fix?

**Comment by nbransby** [comment]
should be this month

**Comment by JoseTripianaZapp** [comment]
I've been working on a fork to test this fix and it doesn't seem to be working. Although the test created in the PR works correctly, it's because the test writes and reads directly with the iOS test. If we check what it's writing into Firebase we can see that it writes 0/1, not true or false. This causes reading data from another platform to fail (although iOS is able to interpret this value as a boolean)
