### ISSUE TITLE
JsonObject deserialization is not working.

### ISSUE THREAD

**Issue by Gery711KO** [GitLiveApp/firebase-kotlin-sdk#500]
The object im trying to deserialize is something like this:
```kotlin
@Serializable
data class SomeDto(
    // ...some primitive fields
    val jsonObjectField: JsonObject = JsonObject(emptyMap()),
)
```

I managed the find where the exception is thrown, but it hides the actual exception for some reason. It would be cool, if you could do a quick fix just for showing the actual exception itself.
![image](https://github.com/GitLiveApp/firebase-kotlin-sdk/assets/96139474/eca87512-0f21-4c5c-b568-af04e844fa6a)
`kotlinx.serialization.SerializationException: Exception during decoding com.package.app.SomeDto jsonObjectField `

**Comment by nbransby** [comment]
You need to use regular POKOs with @Serializable annotation

**Comment by krobert** [comment]
@nbransby belive us, we tried everything, it has the annotation, but its not working for dynamic content:

```
@Serializable
data class Dto(
    val id: String = "",
    val params: Map<String, @Contextual @Serializable(with = AnySerializer::class) Any?>? = null,
) 
```
right now it looks like this, but i tried this also:
```
@Serializable
data class Dto(
    val id: String = "",
     @Contextual
    @Serializable(with = FirebaseMapSerializer::class)
    val input: Map<String, @Contextual Any?>? = emptyMap(),
) 
```
also a lot of combinations, using jsonobject instead of map.

the sdk has this custom implementation of kotlin serialization, there is no way to get the data.
In android firebase sdk i can get the data as a map<string, any> and it works pretty well, but this kmm solution just breaks this.
can we have at least a method for DocumentSnapshot, which doesnt require parsing, just returns the raw value as map<string,any?> like the original sdk?
<img width="714" alt="image" src="https://github.com/GitLiveApp/firebase-kotlin-sdk/assets/6197932/433d83d2-ebfd-4212-bb76-a594b5ec1865">

**Comment by Daeda88** [comment]
Have you tried setting a custom SerializerModule? If you're doing Contextual serialization, you should set a serialization module. 

Like, even on regular serialization this would fail:

```
class TestContextualSerialization() {

    @Serializable
    data class TestData(
        val map: Map<String, @Contextual Any>
    )

    @Test
    fun testSerialization() {
        val value = TestData(mapOf("1" to 1, "2" to "two", "3" to false))
        println(Json.encodeToString(value))
    }
}
```

When using `@Contextual` you still need to provide a Context. See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization

On this SDK, you can access the SerializationModule in your encode or decode Settings:
```
DocumentSnapshot.getData {
  serializersModule = SerializersModule {
      contextual(Any::class, // Set your serializer here)
  }
}
```

Make your

**Comment by Daeda88** [comment]
Digging a little bit deeper into the existing SDKs, For Android we'd have to wrap `CustomClassMapper` somehow, and for iOS `FSTUserDataWriter` to get the same behaviour. It's probably not impossible, but certainly difficult to get a proper _multiplatform_ behaviour.

What would be the correct solution IMO would be:

```
@Serializable
data class Dto(
    val id: String = "",
    val params: Params,
) {
   @Serializable
   data class Params(
       "argumentOne": Int? = null,
       "argumentTwo": String? = null
   )
}
```
Since Im gonna assume you know beforehand which params you are gonna support. Strictly typed data is for sure the recommended way to go.

**Comment by krobert** [comment]
@Daeda88 sorry for late answer, well yeah i know some params and ended up doing the same solution.
Can i ask why didnt you use the original `fun map<string,Object?> getData()` from the sdk? Both ios and android has this and working pretty well, maybe doing the same solution as here, with the kotlin `Result<T>` can fix the issue?
https://github.com/a-sit-plus/KmmResult

**Comment by Daeda88** [comment]
Not the original author, nor member of the actual team, so I can't go into considerations on that. I imagine it has to do with the fact that:

a) Dynamic typing makes little sense in the first place. Either the client or the server needs to know the data type at some point, otherwise why even store it
b) Because this is a multiplatform approach, some customization needs to take place. E.g. a Timestamp is not passed as the platform specific timestamp but as a wrapper class so that its behaviour can be modeled consistently across platforms. So just passing dynamic typing in itself is not good enough.

**Comment by nbransby** [comment]
Yes B is the reason we can't simply expose the original fun map<string,Object?> getData() from the sdks otherwise you would get different types back on different platforms
